// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp_dCdOMLoBGSj7Y6cnTmj5UOR8GAYvfk',
    appId: '1:74124387614:web:eb7e1f353d3441bfa4950f',
    messagingSenderId: '74124387614',
    projectId: 'dum-check',
    authDomain: 'dum-check.firebaseapp.com',
    storageBucket: 'dum-check.firebasestorage.app',
    measurementId: 'G-NRJPPX7BVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Eoj3SZCnUIrmviP550q51J-IUQoZWUY',
    appId: '1:74124387614:android:ec47ec7edcaaed48a4950f',
    messagingSenderId: '74124387614',
    projectId: 'dum-check',
    storageBucket: 'dum-check.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Bl6u7D60OehQlnknh8A6yuS-KpwsALo',
    appId: '1:74124387614:ios:5ad8c7277df9d516a4950f',
    messagingSenderId: '74124387614',
    projectId: 'dum-check',
    storageBucket: 'dum-check.firebasestorage.app',
    iosBundleId: 'com.example.attendanceInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Bl6u7D60OehQlnknh8A6yuS-KpwsALo',
    appId: '1:74124387614:ios:5ad8c7277df9d516a4950f',
    messagingSenderId: '74124387614',
    projectId: 'dum-check',
    storageBucket: 'dum-check.firebasestorage.app',
    iosBundleId: 'com.example.attendanceInterface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp_dCdOMLoBGSj7Y6cnTmj5UOR8GAYvfk',
    appId: '1:74124387614:web:277c0c97c7b7b535a4950f',
    messagingSenderId: '74124387614',
    projectId: 'dum-check',
    authDomain: 'dum-check.firebaseapp.com',
    storageBucket: 'dum-check.firebasestorage.app',
    measurementId: 'G-9LXZSLM39Q',
  );
}
